README.md
This reflects the default port used when running `flask run`.
=> BAU: Fix app local port

frontend/magic_links/templates/magic_link.html
A very simple template was added with instructions to send it to the user once the sign-in link was mailed to the user.
=> magic_link template added for user information

config/environments/default.py
Previously the session cookie value was not set in the test config. This caused an exception when attempting to create a session on the test environment. The same error did not occur on dev because we set the value on that environment here: https://github.com/communitiesuk/funding-service-design-authenticator/blob/fae3d04fb5434d450dd2481e2265931c28b3d3f0/config/environments/dev.py#L13
=> BAU: default session cookie value

manifest.yml
Previously we were setting secrets using `--var` but they were not reaching the application as they need to be explicitly set using variable substitution
See also https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html#variable-substitution
and https://github.com/cloudfoundry/cli/issues/1012#issuecomment-625404004
=> BAU: Use variable substitution to inject secrets

.github/workflows/deploy.yml
Same change as https://github.com/communitiesuk/funding-design-service-workflows/pull/6 as this repo has forked the workflkow
=> BAU: limit test deploys to main

run/gunicorn/config.devtest.py
Previously the Request ID was not getting passed down because PaaS uses a non-standard name for this header.
=> FS-1015: Fix PaaS request ID header

app.py
Swagger did not have correct talisman config loading meaning that inline javascripts were blocked on the docs page (making swagger inaccessible).
=> nonce none on swagger path

api/magic_links/routes.py, config/envs/default.py, openapi/api.yml
following other changes, this purely redirected to another public landing page route so can be safely deleted
=> FS-1229: Remove un-needed landing route

config/envs/production.py
We want to use this as it's easier to use on PaaS.
=> FS-987: use base64 encoded key on prod environment

config/envs/default.py
Will return `None` if not set so shouldn't break any other environments.
=> FS-987: default cookie domain to try and read env var

api/magic_links/routes.py, frontend/magic_links/routes.py, requirements-dev.txt, requirements.in, requirements.txt, tests/test_magic_links.py
I have set it so that the landing page (with continue button) shows,
a/ if the link hasn’t been used, or 
b/ if you’re already logged in.
This means if you click a valid link, go to your dashboard and then click back you can still see the continue button and go forward again.
If you're not logged in and you try to re-use a magic link that you (or someone else) has already used, then you will see the invalid link page
=> FS-1480 restore invalid link page

api/session/auth_session.py, app.py, config/envs/default.py, config/envs/development.py, config/envs/unit_test.py, requirements-dev.txt, requirements.in, requirements.txt
- Enable SameSite session cookie setting by upgrading flask-session to version 0.4.0
- Update talisman initialisation method to use default config dictionary setting approach
- Clearer grouping of config session settings
=> FS-1501 Increase cookie security

.github/workflows/deploy.yml
dependabot cannot share action secrets, the action secrets are required for deploying to environments (dev and test). If dependabot opens a PR then this fix will now prevent deployments to dev. This approach relies on testing to catch any problems with a package bump - when merged the journey will be tested in our test environment before released to higher environments. 
*An alternative to this is to set the deployment secrets as dependabot secrets.
=> prevent dependabot deploys

models/magic_link.py, openapi/api.yml, tests/mocks/redis_magic_links.py, tests/test_magic_links.py
Restores `/search` endpoint removed in #35 but restricts it to non-production environments (for use by End-to-end tests)
=> FS-1133: restore magic link search endpoint on non-prod environments

config/envs/production.py
We are no longer namespacing this with the environment
=> BAU: fix redis service name

manifest-dev.yml, manifest-test.yml
FS-1813 - Adding fund store url into manifests allows authenticator to pull data from teh fund store, and display the correct submission deadline
=> added fund store url to manifests

config/envs/default.py, config/envs/dev.py
- Change default config, pull cookie domain from COOKIE_DOMAIN env var
- If COOKIE_DOMAIN env var is not set, it will default to None
This is needed to persist the `language` cookie when going from frontend -> authenticator.
=> FS-2046: Pull cookie domain from env var

api/sso/routes.py, models/account.py, tests/api_data/post_endpoint_data.json, tests/mocks/msal.py, tests/test_sso.py
- Update create_or_update_account() upsert behaviour to allow users with existing account to have their azure_ad_subject_id updated on first SSO login, while still preventing azure_ad_subject_id from being modified once associated
- Update tests to check correct exception raised
=> FIX: Enable update on first time SSO login on existing account

frontend/user/routes.py, models/account.py, tests/api_data/put_endpoint_data.json, tests/mocks/msal.py, tests/test_signout.py, tests/test_sso.py
- Modify update_account method to log an error if a user with no roles attempts to authenticate, but otherwise allow authentication and session creation to succeed
- Test added to confirm the behaviour above
=> BAU: Modify update_account method to log an error if a user with no roles signs in.

frontend/magic_links/templates/check_email.html, frontend/magic_links/templates/email.html, frontend/magic_links/templates/invalid.html, frontend/magic_links/templates/signed_out.html, frontend/templates/base.html
Sibling PR to https://github.com/communitiesuk/funding-service-design-frontend/pull/243 
Uses same approach as https://github.com/communitiesuk/funding-service-design-frontend/pull/243 to extract the `h1` into a `pageHeading` variable and then pull that into the `title` if specified
=> FS-2190: set unique title tags

.github/workflows/deploy.yml
Disabling e2e tests on Dev as it's giving false positives on some test runs. This is mainly due to the environment being constantly deployed per commit which disrupts the e2e test run.
Evidence that e2e application and assessment passes when running against Test env with the e2e tests not running against Dev:
https://github.com/communitiesuk/funding-service-design-frontend/actions/runs/4222595381
N/A
N/A
=> BAU - Disable e2e tests running against Dev env

.github/workflows/tag-to-release.yaml
Change description
Since moving to an Enterprise org it appears GITHUB_TOKEN has defaulted to restricted permissions as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token so we need to specify the correct permissions for our workflows.
[ - ] Unit tests and other appropriate tests added or updated
[ - ] README and other documentation has been updated / added (if needed)
[ - ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
Screenshots of UI changes (if applicable)
=> tagging action permissions updated

app.py, frontend/magic_links/routes.py
Sentry has logged issues where auth crashes when fund and round ids are not passed as query parameters. This is not the intended usecase as we always expect the user to go through a flow were the fund and round details are passed from frontend to auth, however we still should make sure the app does not crash even if these are not being passed thorugh.
=> bau-auth-service-name-fix

frontend/magic_links/routes.py, models/fund.py, tests/test_magic_links.py
We have now added necessary handling of erroneous fund and round data being passed to the new() and landing() routes in auth. We now return a 404 rather than a 500 when incorrect or missing fund data is passed to these routes.
=> fs-2663-handling-incorrect-fund-round-data

frontend/magic_links/routes.py, frontend/magic_links/templates/check_email.html
request new magic link link redirects to the new() route without setting the appropriate fund and round query params, this PR adds the fix for this.
=> bau-fix-request-new-magic-link

api/magic_links/routes.py, api/session/auth_session.py, frontend/magic_links/routes.py, frontend/magic_links/templates/landing.html, frontend/magic_links/templates/signed_out.html, tests/test_magic_links.py, tests/test_signout.py
Request a new link button was re-directing us to the old get new magic link page which did not have the required fund and round query params. We have now added the fund and round short names as values in the fsd_user_token cookie so that whichever page the user logs out of we are able to pull the appropriate fund and round short names and add them to the url when they click on the request a new link button.
=> fs-2676-update-requesting-new-link

api/session/auth_session.py
This PR fixes the issue were an invalid token causes auth to break as we cannot get fund and round info from it but need to instead return none for fund and round short names.
=> bau-invalid-token-query-params-sign-out

api/session/auth_session.py, api/sso/routes.py, config/envs/default.py, frontend/sso/routes.py, frontend/user/routes.py, openapi/api.yml, requirements-dev.txt, requirements.in, requirements.txt, tests/test_signout.py, tests/test_sso.py
https://trello.com/c/tQ3rDYzh/328-implement-authentication-changes-into-front-end-auth-utils-and-docker-runner
Enables other FSD applications (namely for now, post-award-frontend) to make use of the SSO and Session capability of authenticator. This is enabled by passing a `return_app` query param to authenticator when requesting SSO authentication, so that the app can return back to other applications other than pre-award-assessment. These apps are defined in config and map to return URLs and authorisation BPs.
=> PAB-328: post-award compatibility

config/envs/default.py, config/envs/development.py, frontend/magic_links/routes.py, models/account.py
- Whenever `AUTO_REDIRECT_LOGIN` is set to `True`, we auto redirect to the magic link
- Only set to `True` in development, shouldn't be set to `True` on prod/uat, etc.
--- 
- Pull branch locally
- Try to login to the application via magic link
=> BAU: Auto redirect to magic link on development

models/account.py, models/data.py
This ticket resolves the issues of not being able to login locally via sso thereby blocking testing of sso on local environments.
- session[user] token had no key called roles, therefore whenever the update_account() method was called it kept resetting the roles for the user trying to log in.
- We can see that this only happens locally and not in dev or test environments where we are using the exact same azure test tenant.
- This suggests that the session[user] token in other environments does include a key called roles which grabs the values from the azure ad, but for some reason does not exist when running locally.
- to bypass this, this PR introduces changes that checks whether we are on the local development environment and then sets the roles as found in the account store for the …
=> FS-2304: Local SSO

models/account.py
Have been testing `FS-3024` locally, but now want to test on the test env, due to all envs using the same Azure AD, and the new fund specific role & devolved authority changes, an error has been popping up when I try to login: https://funding-service-design-team-dl.sentry.io/issues/4270641612/?project=4503919190016000&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
This is a temporary fix, so we don't hard fail on roles that we don't know.  
Note that https://github.com/communitiesuk/funding-service-design-authenticator/pull/169 will be updated to account for this in the future, this is just a fix so I can test in the test env.
=> FS-3024: Don't fail on unknown roles

frontend/default/routes.py, models/account.py, requirements-dev.txt, requirements.in, requirements.txt, testing/mocks/mocks/msal.py, tests/api_data/put_endpoint_data.json, tests/test_magic_links.py, tests/test_signout.py
- Add a check for local development, we use roles from the database instead of from Azure AD.
- Update utils so `azure_ad_role_map` changes are picked up
---
https://github.com/communitiesuk/funding-service-design-utils/pull/85
https://github.com/communitiesuk/funding-service-design-account-store/pull/96
https://github.com/communitiesuk/funding-service-design-assessment-store/pull/198
https://github.com/communitiesuk/funding-service-design-assessment/pull/275
=> FS-2990 & FS-2989: Update utils for devolved auth and multi fund

models/data.py
get_round_fail_gracefully() function is currently still causing a 500 when the round is not found, but we need to return an empty round object without causing an error log/ the app to break.
=> bau-get-round-fail-gracefully-warning

.pre-commit-config.yaml, config/envs/dev.py, config/envs/development.py, config/envs/unit_test.py, copilot/environments/addons/funding-service-magic-links.yml
https://dluhcdigital.atlassian.net/browse/FS-3441
- Added pre-commit 'Yelp/detect-secrets' to prevent committing of secrets to code base
- Ignore false positives by marking them with `pragma: allowlist secret`
- disabled the plugin `HexHighEntropyString` which tend to detect lot of false positives
- Add a secret/API key/password to any of the file type
For eg. `API_KEY= "125fdfbdjhbj5989"`
- stage the file & commit it.
- Notice the commit is failed with errors.
=> FS-3441 added yelp hook for secrets

copilot/fsd-authenticator/manifest.yml
- adds the post-award Submit host to manifest envars so that Authenticator can redirect to the Submit tool
=> add post-award Submit host to manifest

api/magic_links/routes.py, frontend/default/routes.py
- In scenarios where a user clicks "continue" on a magic link they've already claimed
- If they still have a token in their browser, we re-direct them to the "/account" page
- This change makes it so we re-direct them to the specific fund/round they're trying to continue to
---
- Request a magic link for [DPIF](https://fsd:fsd@authenticator.uat.gids.dev/service/magic-links/new?fund=dpif&round=r2)
- Open the magic link from your email and hit continue
- You should be on the DPIF specific account page, and can start an application
- Hit back on your browser then continue again
- You should be on the DPIF specific account page, and can start an application (used to be on just /account)
=> BAU: Include fund & round in redirect

api/magic_links/routes.py
- Reformatting based on feedback here https://github.com/communitiesuk/funding-service-design-authenticator/pull/208#discussion_r1362362230
=> BAU: Use urlencode instead of quote

api/sso/routes.py, models/account.py
- When an account/user has no roles, the "roles" key isnt available on the claims coming back from azure
- So we default to an empty list if that is the case, instead of `None`
- Changes length checks to just truthy, which will work on empty or populated list 
---
=> BAU: Fix truthy check on roles

.github/workflows/deploy.yml, manifest-dev.yml, manifest-test.yml
Previously authenticator was not picking changes in the manifest, as the `include_manifest` flag on the workflow was set to false.
Env Vars should be set on Test post-merge/deployment on test
=> BAU: use manifest for authenticator

requirements-dev.in, requirements-dev.txt, requirements.txt
✅ This PR was created by the Combine PRs action by combining the following PRs:
#209 Bump urllib3 from 1.26.12 to 1.26.18
#206 Bump gitpython from 3.1.27 to 3.1.37
#196 bump webdriver-manager from 3.7.0 to 4.0.1
#188 Bump certifi from 2022.6.15 to 2023.7.22
=> Combined PR

frontend/static/src/js/fsd_cookies.js
- Start setting domain with cookie so it persists across access-funding
- If access-funding then we take `access-funding.levellingup.gov.uk`
- If test env we take `test.gids.dev`, local environment is `localhost`
=> BAU: Fixing cookie domain based on prod/test/local env

config/envs/default.py, copilot/fsd-authenticator/manifest.yml
https://dluhcdigital.atlassian.net/browse/FS-3890
Add the true DNS entry alongside the .prod. variant.
Ensure the migration banner flag is a config variable, not hardcoded, and make it false.
=> FS-3890 making migration banner an env var

.github/workflows/copilot_deploy.yml
Correcting the list of paths that trigger a deployment as authenitcator is structured differently to other apps
=> correcting paths for push triggers

frontend/magic_links/routes.py, models/account.py, models/data.py
- For some reason, providing `as_dict` as `False` (default) was returning a dict, contrary to the name... 
- Fixed function implementation and usages to accurately return a dict based on the argument name
=> BAU: Fix as_dict argument of method

frontend/magic_links/routes.py, frontend/magic_links/templates/landing.html, frontend/magic_links/templates/landing_eoi.html, models/round.py, tests/test_magic_links.py
- Fund store has new property `reference_contact_page_over_email`
- We use this to determine whether we show a link to the contact us page, or their email
---
=> FS-4071: Show "contact_us" or email depending on fund

copilot/fsd-authenticator/manifest.yml
FS-4411: Overprovision instance
##Change description
Reduce the number of instance to 1 in Dev and change the ECS launch_type to Fargate-spot.
Unit tests and other appropriate tests added or updated
README and other documentation has been updated / added (if needed)
Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
_Will check after deployment by logging into the ECS console and view the service and instance configuration
Screenshots of UI changes (if applicable)
=> FS-4411:Over-provision instance and change to Fargate-spot

config/envs/default.py
Default AWS region, without this authenticator fails to start-up with
`botocore.exceptions.NoRegionError: You must specify a region.`
Error `botocore.exceptions.NoRegionError: You must specify a region.` no longer fails at start-up
=> BAU: Default AWS region

api/magic_links/routes.py, app.py, config/envs/default.py, config/envs/development.py, models/account.py, openapi/api.yml, requirements-dev.in, requirements.in, requirements.txt, tests/conftest.py, tests/test_account.py, tests/test_healthchecks.py, tests/test_magic_links.py, tests/test_signout.py
- Removes the 'Create magic link' endpoint
- Creates a unit test fixture to create a magic link for testing of auth
- Updates tests to use that new fixture
- `swagger-ui` now installed only as a dev dependency and the ui is only publish when running locally.
Login and authenticate with a magic link as usual.
=> FS-4547 removing magic links create endpoint

api/session/auth_session.py, api/sso/routes.py, config/envs/unit_test.py, frontend/sso/routes.py, tests/test_signout.py, tests/test_sso.py
Adds ability to set a `return_path` where a `return_app` is specified.
This is useful in order to customise the redirect for signed out users where we want them to return to a specific route post sign-in rather than being returned to the homepage
Note in order to work end-to-end with services this will require a change in the utils library which will be introduced in a subsequent PR
(when running post-award docker runner)
Go to: `http://localhost:4004/service/sso/signed-out/no_token?return_app=post-award-frontend&return_path=/data-glossary`
Click login
Follow Microsoft sign-in flow
Should be redirected to data-glossary on data-frontend
=> FPASF-376: add return_path argument for sign-out/sign-in 

config/envs/development.py, tests/api_data/get_endpoint_data.json
- Pull in COOKIE_DOMAIN from env, if defined, even in dev environment
- Add mock data for post award browser tests to generate magic links
FPASF-287
=> Support post-award browser tests

api/magic_links/routes.py, api/session/auth_session.py, frontend/magic_links/routes.py, pytest.ini, tests/test_signout.py, tests/test_sso.py
https://dluhcdigital.atlassian.net/browse/FPASF-491
Turns all warnings into errors so that they can be caught early and developers are required to handle them (either by fixing the code or explicitly ignoring the error).
This ignores a few errors from our dependencies, and fixes others, such as:
* `logger.warn` being deprecated in favour of `logger.warning`
* setting the parser explicitly for `BeautifulSoup`
* removing some no-longer-used settings from `pytest.ini` (we seemingly don't use pytest-reportportal any more)
* declaring a pytest marker in `pytest.ini` (new_account)
=> Turn warnings into errors when running pytest

config/envs/default.py, tests/api_data/get_endpoint_data.json
The old COF support email was using the levellingup domain ( [cof@levellingup.gov.uk](mailto:cof@levellingup.gov.uk) ). This has been updated to the communities domain ( [cof@communities.gov.uk](mailto:cof@communities.gov.uk) )
=> Update COF support email from levellingup domain to communities

api/sso/routes.py, tests/test_sso.py
Previously we were displaying the error from Azure AD error back to the user (I guess for developer convenience but this is not best practice security wise) this changes it to log the error internally and display a generic 500 message
Make secret key invalid locally, 500 page should display and error should be logged in console.
=> BAU: log error in case of get-token failure but display generic 500 page

.gitignore
Adds a `.python-version` file that can be read by `pyenv` or `uv` when creating virtual environments. Should simplify setup, where the docker-runner's `install-venv-all-repos.sh` script can sometimes pick the wrong python if you have multiple installed.
=> Add .python-version

copilot/fsd-authenticator/manifest.yml
Remove recreate deploy strategy on test, as this causes downtime during deployment e.g. https://communities-govuk.slack.com/archives/C0478PGHL1E/p1730369264494489?thread_ts=1730094584.136009&cid=C0478PGHL1E
This will revert to the default as described here: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment
Should deploy without downtime on test
=> BAU: Remove recreate deploy strategy on test

copilot/fsd-authenticator/manifest.yml
This will help us migrate from the "microservice"-y fund-store to a more consolidated pre-award-stores service.
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-108
=> Read fund-store host from parameter store

copilot/fsd-authenticator/manifest.yml
=> FLS-795: Basic auth added

.vscode/settings.json, config/envs/default.py, frontend/magic_links/routes.py, models/account.py, models/magic_link.py, models/notification.py, openapi/api.yml, tests/test_account.py, tests/test_magic_links.py, tests/test_notification.py
https://mhclgdigital.atlassian.net/browse/FSPT-137
Our end-to-end test suite is currently taking quite a long time to run, as many of the tests run sequentially. The main reason for needing them to run sequentially is that some tests login as the same user, and the login attempts are in conflict. This conflict is not handled well by the end-to-end tests and concurrent logins are not well supported by authenticator. Authenticator allows multiple login sessions to exist at once, but does not allow multiple unredeemed magic links to exist for one account at the same time. Furthermore, the end-to-end tests use a "list all magic links" endpoint on authenticator and then grab the top magic link off the stack. This link isn't necessarily associated with the account that they are trying to log in …
=> Set GOV.UK Notify references in emails for magic links

copilot/fsd-authenticator/manifest.yml
Trace all requests on pre-prod
The production value is based on utils default from: https://github.com/communitiesuk/funding-service-design-utils/blob/b65c285328847640f8622c368595938b60e44d02/fsd_utils/sentry/init_sentry.py#L19C59-L19C63 we could possibly increase this in future, but previously a combination of bot traffic and looping errors have used all our quota.
More requests should be traced post-deployment
=> FSPT-123: Trace all requests on pre-prod

config/envs/default.py, copilot/fsd-authenticator/manifest.yml, pyproject.toml, uv.lock
[Add authentication for FAB](https://mhclgdigital.atlassian.net/browse/FS-4805)
See ticket for wider context. This PR specifically is to add FAB to the list of safe return apps alongside the other frontend apps that use authentication - Submit and Find (Assess is handled in a bespoke way).
Form Designer is also added pre-emptively, to prevent the need for another PR when work on this ticket - [Add authentication for Form Designer](https://mhclgdigital.atlassian.net/browse/FS-4794) - begins.
=> FS-4805 - Add FAB and Form Designer to the list of safe return apps

app.py, build.py, frontend/templates/base.html, frontend/templates/head.html, pyproject.toml, uv.lock
Currently the authenticator app services web pages that fallback on the `arial` font and don't have the GOV.UK crown as the Favicon. This gives in inconsistent user experience, looks visually broken and doesn't follow the guidance to use "GDS Transport" on gov.uk domains.
Tell the flask app to serve static assets from the `/assets` path. As we're not customising our styles from the base design system SCSS we'll use the default path included in the pre-built CSS.
The relative paths for the `/fonts` and `/images` will now line up and the appropriate font should be used.
Remove custom logic for manipulating the asset path in the CSS thats copied over, that is error prone as evidenced by the fact it would update for the font files but not the favicon. (Instead we adjust where static files are …
=> FSPT-156 Fix serving static fonts and favicon
