communitiesuk/funding-service-design-authenticator

- .github/workflows/deploy.yml
- .gitignore
- README.md
- api.yml
- api/magic_links/routes.py
- app.py
- build.py
- config/environments/default.py
- frontend/assets.py
- frontend/default/routes.py
- frontend/magic_links/routes.py
- frontend/magic_links/templates/invalid.html
- frontend/static/src/scss/main.scss
- frontend/templates/404.html
- frontend/templates/500.html
- frontend/templates/base.html
- frontend/templates/footer.html
- frontend/templates/head.html
- frontend/templates/header.html
- frontend/templates/index.html
- requirements.txt
- tests/test_magic_links.py
- Add frontend module with static assets & govuk-frontend build process
- Added invalid link page
- Update /magic-links/{link_id} GET endpoint to redirect to new invalid link error page at /service/magic-links/invalid route
> FS-891 magic link error page

- frontend/magic_links/templates/invalid.html
- tests/test_magic_links.py
Update text as agreed with design
> FS-1014: update invalid page content based on design feedback

- api.yml
- api/magic_links/routes.py
- config/environments/default.py
- frontend/magic_links/routes.py
- frontend/magic_links/templates/landing.html
- models/magic_link.py
- tests/test_magic_links.py
Prevent magic links being "taken" by bots
> FS-924 magic landing page

- frontend/magic_links/templates/email.html
Update backlink on email page to only show if request.referrer url property exists
> FIX: FS-864 Correct backlink to only show if request.referrer url property exists

- manifest-dev.yml
- manifest-test.yml
Bind app to log drain so logs are retained
> FS-1015: send logs to logit log drain

- api/session/auth_session.py
- config/envs/default.py
- config/envs/dev.py
- config/envs/development.py
- manifest-dev.yml
Added cross-domain auth cookie setting
> FS-1163 Cross-domain cookie-setting added

- .gitignore
- config/envs/default.py
- manifest-dev.yml
- manifest-test.yml
- models/magic_link.py
Part of work on FS-1163 to implement custom domain
> updated magic link url to remove account id as this comes from the jwt

- .github/workflows/deploy.yml
- config/envs/dev.py
- config/envs/test.py
- manifest-test.yml
Added route for custom domain and set cookie domain for test env
> Fs 1163 adding route for custom domain in test

- manifest-dev.yml
Use new custom domain whilst previous one is blocked.
> BAU: custom domain

- manifest-test.yml
Replicates the change from #37 on the test environment
> BAU: use temporary custom domain on test

- tests/api_data/get_endpoint_data.json
- tests/api_data/post_endpoint_data.json
> Correct expected keys on account_store endpoint responses

- .github/workflows/deploy.yml
- app.py
- manifest-dev.yml
- manifest-test.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/mocks/redis_magic_links.py
- tests/test_healthchecks.py
Added healthchecks:
- Flask Running
- Redis available
> Fs 1306 healthchecks

- .pre-commit-config.yaml
- config/envs/default.py
> FS-1323 Extend fsd (jwt) session expiry to 1 day

- frontend/templates/header.html
https://digital.dclg.gov.uk/jira/browse/FS-1332
removed hyperlinks
> fs-1332-remove-hyperlink-from-header

- api/magic_links/routes.py
- api/session/auth_session.py
- models/account.py
- openapi/api.yml
Removing this route as it is insecure to make magic links publicly available
> FS-1229 remove list magic links route

- frontend/magic_links/forms.py
- frontend/magic_links/templates/check_email.html
- frontend/magic_links/templates/email.html
> UI tweaks for COF launch

- api/session/auth_session.py
- config/envs/default.py
- config/envs/development.py
- config/envs/unit_test.py
Set secure flags on JWT cookie (as suggested in IT Healthcheck)
> FS-1501: set secure attributes on JWT cookie

- tests/api_data/get_endpoint_data.json
- tests/api_data/post_endpoint_data.json
Removed references to the account stores application list.
> FS-1521-removed-references-to-app-list

- config/envs/default.py
- config/envs/unit_test.py
- models/account.py
- tests/api_data/get_endpoint_data.json
- tests/api_data/post_endpoint_data.json
- tests/mocks/__init__.py
- tests/mocks/application_methods.py
- tests/test_magic_links.py
- Add CREATE_APPLICATION_ON_ACCOUNT_CREATION config flag defaulted to False
- Use as a toggle to enable/disable auto-creation of applications on account creation
> FS-1622 Prevent auto-creation of applications on account creation

- app.py
- manifest-dev.yml
- manifest-test.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
Adds sentry integration using utils function
> FS-1401: add sentry integration

- api/session/auth_session.py
- config/envs/default.py
- requirements-dev.txt
- requirements.in
- requirements.txt
Adding new SCRF token time limit from new fsd-utils
> fs-1625-adding-new-csrf-tokens

- .github/workflows/deploy.yml
- requirements-dev.txt
- requirements.in
- requirements.txt
Change to include https://github.com/communitiesuk/funding-service-design-utils/pull/48
> FS-1773: Bump fsd-utils version for locale sniffing

- api/session/auth_session.py
- api/sso/routes.py
- requirements-dev.txt
- requirements.txt
Implements utils feature added in https://github.com/communitiesuk/funding-service-design-utils/pull/55
Note: most changes are enforced by linter, only `clear_sentry()` is new functionality
> FS-2159: clear sentry user on sign out

- config/envs/default.py
- pytest.ini
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/test_healthchecks.py
Bumping utils version and retrieving default IDs from there
> getting default IDs from utils

- .github/workflows/tag-to-release.yaml
Run action on merge to pick up workflow changes from https://github.com/communitiesuk/funding-service-design-workflows/pull/34
> FS-2172: Run tag task on merge

- README.md
- api/session/auth_session.py
- docs/README.md
> BAU: Docs update

- frontend/templates/footer.html
https://digital.dclg.gov.uk/jira/browse/FS-2202
> More descriptive footer title

- config/envs/default.py
- frontend/magic_links/routes.py
Updated the magic links landing page to use new URL for the 'all questions' link. Goes along with changes to the frontend and fund-store.
> Bau all qs r2w3

- frontend/templates/header.html
Update feedback URL for Window 3
> FS-2340: update feedback URL

- .github/workflows/deploy.yml
Added environment var for the Assessment url, so that the assessment e2e test doesn't fail to run in the pipeline
N/A
N/A
> BAU - Add env var for Assessment e2e test

- .github/workflows/deploy.yml
https://digital.dclg.gov.uk/jira/browse/FS-1200
Added assessment store url to enable performance tests for Assessment store.
N/A
N/A
> FS-1200: Enable performance tests for Assessment store to run in the pipelines

- api/magic_links/routes.py
- api/session/auth_session.py
- frontend/magic_links/routes.py
- frontend/magic_links/templates/check_email.html
- frontend/magic_links/templates/invalid.html
- frontend/magic_links/templates/signed_out.html
Adding fund and round query params to link expiry page to redirect to appropriate get new magic link page
> bau-link-expired-multifund

- api/session/auth_session.py
We're having issues in test environment that we're not having locally and are therefore adding extra logging to get the visibility on these issues: this PR focuses on sign-out issues related to validating user tokens.
> bau-add-logging-on-pyjwt-error

- .pre-commit-config.yaml
- frontend/magic_links/templates/check_email.html
- frontend/magic_links/templates/email.html
- frontend/magic_links/templates/invalid.html
- frontend/magic_links/templates/landing.html
- frontend/magic_links/templates/magic_link.html
- frontend/magic_links/templates/signed_out.html
- frontend/sso/templates/sso_signed_out.html
- frontend/templates/404.html
- frontend/templates/500.html
- frontend/templates/base.html
- frontend/templates/index.html
- frontend/user/templates/user.html
- Adds djLint to our pre-commit config on authenticator
- Have run djLint once and fixed all the existing issues
---
> FS-2705: Add djLint to pre-commit and reformat files

- manifest-test.yml
We need to define this to get our Auth flow to work, see related code: https://github.com/communitiesuk/funding-service-design-authenticator/blob/9ccbfefa9511a76f24aae85f7144bdcec2944f5e/config/envs/default.py#L163
Post-Award team will test post-merge
> BAU: Add post-award host

- app.py
- config/envs/default.py
- frontend/default/routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2787
Fixed broken contact us url from following pages
1. Magic link landing page
2. Tasklist page
3. Form pages
4. 404 error pages
5. "You are not logged in" page
> fix broken contact us page

- app.py
- config/envs/default.py
- frontend/default/routes.py
https://digital.dclg.gov.uk/jira/browse/FS-2787
Fixed broken contact us url from following pages
Magic link landing page
Tasklist page
Form pages
404 error pages
"You are not logged in" page
> fix broken contact us url for sign out page

- frontend/templates/header.html
- Update feedback url
- https://forms.office.com/Pages/ResponsePage.aspx?id=EGg0v32c3kOociSi7zmVqFJBHpeOL2tNnpiwpdL2iElURUY1WkhaS0NFMlZVQUhYQ1NaN0E4RjlQMC4u
> BAU: Update feedback url

- frontend/magic_links/routes.py
- frontend/magic_links/templates/landing.html
hide all questions link for funds that don't need this
> fs-2847-all-questions-link

- api/sso/routes.py
- models/account.py
fixing sso bugs and removing redundant code related to roles in development config
> fs-3010-sso-bugs

- .github/workflows/deploy.yml
- .github/workflows/package.yml
- .github/workflows/tag-to-release.yml
- Procfile
- README.md
https://dluhcdigital.atlassian.net/browse/FS-3203
Add paketo build and include it in the workflow
Checked container boots and begins producing output
> FS-3203 - Add paketo build and include in workflow

- api/session/auth_session.py
- config/envs/default.py
- tests/test_magic_links.py
- tests/test_signout.py
Sepreating the fund and round values in the fsd_user_token cookie to a separate user_fund_round_cookie so that when a user's session has expired they are still bale to access the sign in button/ route via the signed_out page.
> fs-3000-fund-round-cookie

- .github/workflows/copilot.yml
https://dluhcdigital.atlassian.net/browse/FS-3278
Dummy copilot workflow
> FS-3278 Add dummy copilot workflow

- tests/test_account.py
https://dluhcdigital.atlassian.net/browse/FS-3323
- Added unittests for the PR https://github.com/communitiesuk/funding-service-design-authenticator/pull/178
> add unittests for 'create_or_update_account'

- .github/workflows/deploy.yml
https://dluhcdigital.atlassian.net/browse/FS-3080
Separate out AWS pre-deploy
> FS-3080 add pre deploy

- .github/workflows/deploy.yml
https://dluhcdigital.atlassian.net/browse/FS-3414
Change outdated reference to fds to fsd.
> FS-3414 Amend fds to fsd

- config/envs/default.py
Updating path to static resources at runtime now we compile them to `frontend/static/dist`
> fs-3313 updating static resources path

- api/sso/routes.py
- config/envs/default.py
Use correct endpoint to show current user only.
Hit `/sso/graph-call` should show current user only
> Use /me endpoint for graph call

- models/account.py
- testing/mocks/mocks/msal.py
- tests/api_data/put_endpoint_data.json
Role cleaning is no longer needed as the deprecated roles are no longer being used.
> remove role cleaning logic

- app.py
- frontend/templates/404.html
- frontend/templates/500.html
- frontend/templates/head.html
- models/fund.py
- Replace hardcoded COF metadata & names from 404/500s
> BAU: Fix metadata on frontend

- .github/workflows/copilot_deploy.yml
- .github/workflows/deploy.yml
https://dluhcdigital.atlassian.net/browse/FS-3337
Bring copilot into line with other repos and put post-deploy into it.
> FS-3337 - split out copilot and add post-deploy tests

- manifest-test.yml
Add submit host, this makes the existing PaaS test env consistent with the copilot one as per: https://github.com/communitiesuk/funding-service-design-authenticator/blob/29d576101b3b63eba84562f76cfcc8b4aaaf9287/copilot/fsd-authenticator/manifest.yml#L53
Authenticator should redirect to submit host after deployment
> BAU: Add submit host

- models/account.py
- tests/test_sso.py
- This log is unnecessary as the user will get re-directed to an appropriate front-end page which allows them to action
- Also for post award this is always shown, so sentry spams us in slack which is slowly making us ignore sentry errors
---
> BAU: Remove unnecessary log

- config/envs/default.py
- frontend/templates/base.html
- frontend/templates/head.html
Added GA 4 to authenticator and CSP for the script and google tag calls
> added google analytics setup to authenticator pages

- app.py
- frontend/templates/base.html
- frontend/templates/head.html
> moved the GA code behind env var

- copilot/fsd-authenticator/manifest.yml
Add production config overrides for post-award apps
Can test after production deployment
> SMD-208: add production config

- config/envs/default.py
> BAU: Add google analytics url

- app.py
- config/envs/default.py
- frontend/templates/base.html
- frontend/templates/head.html
removed google analytics toggle in place of google consent management. setting default to denied
> Removed GA env var toggle and added consent default to GA

- .github/workflows/copilot_deploy.yml
https://dluhcdigital.atlassian.net/browse/FS-3718
The name of the workflow was wrong, so this enables us to test changes to AWS deployment from a branch for the next stage.
> FS-3718 - Fix name of copilot deploy so we can test on a branch

- .github/workflows/copilot_deploy.yml
> Bau concurrency workflow

- copilot/fsd-authenticator/manifest.yml
* Adding uat and production values to copilot config
+ref: FS-3780
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)
- [*] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3780 Updating manifest

- .github/workflows/copilot_deploy.yml
Adding a quick check to confirm what copilot sees as an environment is what the workflow sees as the environment
+ref: FS-3780
+semver: minor
> FS-3780 Confirm env in copilot

- copilot/fsd-authenticator/manifest.yml
* To allow for a smoother bootup, increase CPU to deal with the initial spikes in CPU usage.
+ref: BAU
+semver: minor
> BAU - Increasing CPU requirements

- .github/workflows/copilot_deploy.yml
> Remove unneeded E2E parameter

- .github/workflows/copilot_deploy.yml
- .github/workflows/deploy.yml
- copilot/fsd-authenticator/manifest.yml
* Increase the resources required for the authenticator
* Update the deploy workflow to make more sense
+ref: FS-3797
+semver: minor
> FS-3797 - Update deployment resources

- .github/workflows/copilot_deploy.yml
- copilot/fsd-authenticator/manifest.yml
Amend production to prod for pre-award URLs
> FS-3797 - Amend production to prod for deployment

- frontend/magic_links/templates/email.html
- frontend/magic_links/templates/landing.html
-  Add data-qa attribute for E2E tests
> BAU: Add data-qa attribute for E2E tests

- app.py
- frontend/static/src/js/fsd_cookies.js
- frontend/templates/head.html
- Fix when we load the cookie banner, only after dom content loaded
> BAU: Fix when we load the cookie banner, only after dom content loaded

- copilot/fsd-authenticator/manifest.yml
> BAU: Update manifest.yml

- README.md
Updated Authenticator to use shared readme template
> FSP 616 use shared template authenticator

- .github/CODEOWNERS
Adding codeowners file, as this will allow us to automatically request reviews from each of pre-award and post-award teams when creating PRs
https://github.com/orgs/community/discussions/49633
> fs-4014 adding codeowners file

- frontend/magic_links/routes.py
- frontend/magic_links/templates/email.html
- frontend/magic_links/templates/landing_eoi.html
https://dluhcdigital.atlassian.net/browse/FS-4073
https://dluhcdigital.atlassian.net/browse/FS-4074
- Added `EOI` landing page
- Added modifications for `EOI` in email page
linked PR https://github.com/communitiesuk/funding-service-design-frontend/pull/535
> FS-4073 4074 EOI fixes

- frontend/magic_links/templates/landing_eoi.html
https://dluhcdigital.atlassian.net/browse/FS-4074
Minor EOI form bug fixes
> FS-4074 EOI-fixes

- frontend/magic_links/routes.py
- models/round.py
- tests/test_magic_links.py
- Start consuming new `is_expression_of_interest` property instead of checking the short name
---
> FS-4232: Add "is_expression_of_interest" as a proper round property

- frontend/magic_links/routes.py
- frontend/magic_links/templates/landing.html
- frontend/magic_links/templates/landing_eoi.html
https://dluhcdigital.atlassian.net/browse/FS-4398
- Contact details updated for COF-R4W2 and COF-EOI
- Go through the pages mentioned in the ticket and verify changes
> FS-4398: Contact details updated for COF-R4W2 and COF-EOI

- .github/workflows/copilot_deploy.yml
Updating run name to remove dev from auto deploys
> upating run name

- copilot/fsd-authenticator/manifest.yml
remove additional alias as this is not being used
> BAU: remove additional alias

- models/fund.py
- tests/test_fund.py
Bugfix: Fix to handle Inavlid(None) fund_short_name
- [ x] Unit tests and other appropriate tests added or updated
> Bugfix:  handle Inavlid fund_short_name

- requirements-dev.txt
- requirements.in
- requirements.txt
Upgrade utils package.
- packages seem to not have breaking changes
- tests are passing
- tested SSO on local with our test AD
- tested partly magic link (but I struggled to do it all)
> Upgrade fsd utils version

- README.md
Follow-up to #347 Update readme to reflect changed branch protection rules
> BAU: reflect updated approval process

- config/envs/default.py
- config/envs/development.py
- config/envs/unit_test.py
- tests/test_fund.py
Removes some config that didn't vary between environments
Moves config only used by Unit Tests to Unit Test config
This is a refactor, tests should pass
> FSPT-72: cleanup config

- config/envs/default.py
- frontend/default/routes.py
- frontend/magic_links/routes.py
- frontend/magic_links/templates/landing.html
- frontend/magic_links/templates/landing_eoi.html
- frontend/templates/404.html
- frontend/templates/partials/contact_details.html
- frontend/user/routes.py
- frontend/user/templates/user.html
- tests/test_errors.py
- tests/test_magic_links.py
- tests/test_signout.py
https://mhclgdigital.atlassian.net/browse/FLS-870
- apply and assess service desks urls added as env vars
- code refactor
- tests updated
> Service desk urls
